### ISSUE TITLE
hashes are too long

### ISSUE THREAD

**Issue by ryanburnette** [ryanburnette/hash-assets#1]
I'm having a lot of situations where the hashes are making the file names too long.

@coolaj86 Do you have any advice for me on how best to address this?

**Comment by coolaj86** [comment]
What qualifies “too long”?

I’d say just truncate the hash to 128 bits or so.

**Comment by ryanburnette** [comment]
I'm not sure what qualifies. I had to rename some asset files because the filenames were too long and I got build errors.

I'll truncate.

**Comment by ryanburnette** [comment]
Limited to 20 char.
