### ISSUE TITLE
multiple references

### ISSUE THREAD

**Issue by ryanburnette** [ryanburnette/hash-assets#3]
I think it's failing when there are multiple references, which CAN happen.

**Comment by solderjs** [comment]
Indeed, the coding singularity has FAILED:

```js
"aaaaaaaaaaaaa".replace('a', 'A')
```

```txt
"Aaaaaaaaaaaaa"
```

**Comment by ryanburnette** [comment]
i can patch it

**Comment by solderjs** [comment]
I think you have to convert them to a RegExp because `.replaceAll` isn't supported yet in modern browsers or node.

This should come in handy:
https://stackoverflow.com/a/6969486/151312

```js
function escapeRegExp(string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); // $& means the whole matched string
}
```

**Comment by ryanburnette** [comment]
fixed
